spring:
  application:
    name: restful-web-services

  datasource:
    url: jdbc:h2:mem:test_db
    #http://localhost:****/h2-console

  jpa:
    defer-datasource-initialization: true #For execute data.sql
    show-sql: true

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework: info

      hibernate:
        jdbc:
          bind: trace

management:
  endpoints:
    web:
      exposure:
        include:
          - "*" # Not recommendable for production

